version: "3.7"

services:
    nextjs:
        container_name: sammwise-app
        build:
            context: .
            dockerfile: docker/Dockerfile
        restart: unless-stopped
        networks:
            - samm-network
        ports:
            - "127.0.0.1:3500:3500"
        environment:
            - NODE_ENV=production
            - PORT=3500

networks:
    samm-network:
        driver: bridge