const c07_8 = () => ({ "type": "panel", "name": "C7.8 Source Attribution & Citation Integrity", "elements": [
  {
    "type": "radiogroup",
    "id": "d3403cf78f0a097c8b47ce21a11b1ffb",
    "name": "q_c07_7_8_1",
    "title": "[7.8.1] Verify that responses generated using retrieval-augmented generation (RAG) include attribution to the source documents that grounded the response, and that attributions are derived from retrieval metadata rather than generated by the model.",
    "description": "Level: 1 | Role: D/V",
    "choices": [
      {
        "value": 0,
        "weight": 1,
        "text": "No"
      },
      {
        "value": 0.25,
        "weight": 1,
        "text": "Yes, for some"
      },
      {
        "value": 0.5,
        "weight": 1,
        "text": "Yes, for most"
      },
      {
        "value": 1,
        "weight": 1,
        "text": "Yes, for all"
      }
    ]
  },
  {
    "type": "radiogroup",
    "id": "2816aadf408fa28d75f3b21a38a0d5e6",
    "name": "q_c07_7_8_2",
    "title": "[7.8.2] Verify that each sourced claim in a RAG-grounded response can be traced to a specific retrieved chunk, and that the system detects and flags responses where claims are not supported by any retrieved content before the response is served.",
    "description": "Level: 3 | Role: V",
    "choices": [
      {
        "value": 0,
        "weight": 1,
        "text": "No"
      },
      {
        "value": 0.25,
        "weight": 1,
        "text": "Yes, for some"
      },
      {
        "value": 0.5,
        "weight": 1,
        "text": "Yes, for most"
      },
      {
        "value": 1,
        "weight": 1,
        "text": "Yes, for all"
      }
    ]
  }
], "title": "C7.8 Source Attribution & Citation Integrity", "state": "expanded" });
export default c07_8;