// Portuguese (Brazil) translations for Survey.js
import { surveyLocalization } from 'survey-core';

const portugueseTranslation = {
  // Common strings
  pagePrevText: "Anterior",
  pageNextText: "Próximo",
  completeText: "Concluir",
  previewText: "Visualizar",
  editText: "Editar",
  startSurveyText: "Iniciar",
  otherItemText: "Outro (descrever)",
  noneItemText: "Nenhum",
  selectAllItemText: "Selecionar Todos",
  progressText: "Página {0} de {1}",
  indexText: "{0} de {1}",
  panelDynamicProgressText: "Registro {0} de {1}",
  questionsProgressText: "Respondeu {0}/{1} perguntas",
  emptySurvey: "Não há perguntas visíveis no questionário.",
  completingSurvey: "Obrigado por completar o questionário!",
  completingSurveyBefore: "Nossos registros mostram que você já completou este questionário.",
  loadingSurvey: "O questionário está carregando...",
  placeholder: "Selecione...",
  value: "valor",
  requiredError: "Por favor, responda a pergunta.",
  requiredErrorInPanel: "Por favor, responda pelo menos uma pergunta.",
  requiredInAllRowsError: "Por favor, responda as perguntas em todas as linhas.",
  numericError: "O valor deve ser numérico.",
  minError: "O valor não deve ser menor que {0}",
  maxError: "O valor não deve ser maior que {0}",
  textMinLength: "Por favor, insira pelo menos {0} caracteres.",
  textMaxLength: "Por favor, insira menos de {0} caracteres.",
  textMinMaxLength: "Por favor, insira mais de {0} e menos de {1} caracteres.",
  minRowCountError: "Por favor, preencha pelo menos {0} linhas.",
  minSelectError: "Por favor, selecione pelo menos {0} variantes.",
  maxSelectError: "Por favor, selecione não mais de {0} variantes.",
  numericMinMax: "O '{0}' deve ser igual ou maior que {1} e igual ou menor que {2}",
  numericMin: "O '{0}' deve ser igual ou maior que {1}",
  numericMax: "O '{0}' deve ser igual ou menor que {1}",
  invalidEmail: "Por favor, insira um e-mail válido.",
  invalidExpression: "A expressão: {0} deve retornar 'true'.",
  urlRequestError: "A requisição retornou erro '{0}'. {1}",
  urlGetChoicesError: "A requisição retornou dados vazios ou a propriedade 'path' está incorreta",
  exceedMaxSize: "O tamanho do arquivo não deve exceder {0}.",
  otherRequiredError: "Por favor, insira o outro valor.",
  uploadingFile: "Seu arquivo está sendo carregado. Por favor, aguarde alguns segundos e tente novamente.",
  loadingFile: "Carregando...",
  chooseFile: "Escolher arquivo(s)...",
  noFileChosen: "Nenhum arquivo escolhido",
  filePlaceholder: "Arraste e solte um arquivo aqui ou clique no botão abaixo e escolha um arquivo para carregar.",
  confirmDelete: "Você quer deletar o registro?",
  keyDuplicationError: "Este valor deve ser único.",
  addColumn: "Adicionar Coluna",
  addRow: "Adicionar Linha",
  removeRow: "Remover",
  emptyRowsText: "Não há linhas.",
  addPanel: "Adicionar novo",
  removePanel: "Remover",
  choices_Item: "item",
  matrix_column: "Coluna",
  matrix_row: "Linha",
  multipletext_itemname: "texto",
  savingData: "Os resultados estão sendo salvos no servidor...",
  savingDataError: "Ocorreu um erro e não foi possível salvar os resultados.",
  savingDataSuccess: "Os resultados foram salvos com sucesso!",
  saveAgainButton: "Tentar novamente",
  timerMin: "min",
  timerSec: "seg",
  timerSpentAll: "Você gastou {0} nesta página e {1} no total.",
  timerSpentPage: "Você gastou {0} nesta página.",
  timerSpentSurvey: "Você gastou {0} no total.",
  timerLimitAll: "Você gastou {0} de {1} nesta página e {2} de {3} no total.",
  timerLimitPage: "Você gastou {0} de {1} nesta página.",
  timerLimitSurvey: "Você gastou {0} de {1} no total.",
  clearCaption: "Limpar",
  signaturePlaceHolder: "Assine aqui",
  chooseFileCaption: "Escolher arquivo",
  takePhotoCaption: "Tirar Foto",
  photoPlaceholder: "Clique no botão abaixo para tirar uma foto usando a câmera.",
  fileOrPhotoPlaceholder: "Arraste e solte ou selecione um arquivo para carregar ou tirar uma foto usando a câmera.",
  replaceFileCaption: "Substituir arquivo",
  removeFileCaption: "Remover este arquivo",
  booleanCheckedLabel: "Sim",
  booleanUncheckedLabel: "Não",
  confirmRemoveFile: "Você tem certeza que deseja remover este arquivo: {0}?",
  confirmRemoveAllFiles: "Você tem certeza que deseja remover todos os arquivos?",
  questionTitlePatternText: "Título da Pergunta",
  modalCancelButtonText: "Cancelar",
  modalApplyButtonText: "Aplicar",
  filterStringPlaceholder: "Digite para pesquisar...",
  emptyMessage: "Não há dados para exibir",
  noEntriesText: "Não há entradas ainda.\nClique no botão abaixo para adicionar uma nova entrada.",
  more: "Mais",
  tagboxPlaceholder: "Digite para adicionar uma tag...",
  selectToRankEmptyRankedAreaText: "Todas as opções estão classificadas",
  selectToRankEmptyUnrankedAreaText: "Arraste e solte as opções aqui para classificá-las"
};

// Add Portuguese locale to Survey.js
surveyLocalization.locales["pt"] = portugueseTranslation;
surveyLocalization.localeNames["pt"] = "Português";

