name: vet OSS Components

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

permissions:
  # Required for actions/checkout@v4
  contents: read

  # Required for writing pull request comment
  issues: write
  pull-requests: write

  # Required for uploading findings to Github security tab
  security-events: write

jobs:
  vet:
    name: vet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Run vet
        id: vet
        uses: safedep/vet-action@v1.1.6
        with:
          policy: .github/policies/vet-policy.yml
        env:
          # Required for writing pull request comment
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install vet CLI
        run: |
          curl -sSfL https://github.com/safedep/vet/releases/latest/download/vet-linux-amd64.tar.gz | tar -xz
          sudo mv vet /usr/local/bin/
          vet --version

      - name: Fail on critical vulnerabilities
        run: |
          echo "Checking for critical or high vulnerabilities..."
          vet scan -D . \
            --policy .github/policies/vet-policy.yml \
            --filter-fail